Initial introduction of idr_keypair_file (WIP)
IDR/ansible-role-openstack-idr-keypairs pull request #1
Opened 2017-03-20 16:14 UTC by joshmoore

Migrated from https://github.com/manics/infrastructure/pull/4

2017-03-21 10:42 UTC, manics requested changes

2017-03-21 10:42 UTC, manics commented on tasks/main.yml
> +    public_key_file: "{{ idr_keypair_file }}"
Delete this line

2017-04-21 13:57 UTC, joshmoore commented
@manics: this ok now as 1.1.0?

2017-04-21 16:03 UTC, manics commented
I haven't tested this but it looks fine to me.

2017-04-24 07:04 UTC, merged